# Generated by Django 2.2 on 2021-02-05 06:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='state',
            field=models.CharField(choices=[('tentative', 'tentative'), ('confirmed', 'confirmed'), ('error', 'error'), ('declined', 'declined'), ('completed', 'completed'), ('cancelled_by_owner', 'cancelled_by_owner'), ('cancelled_by_customer', 'cancelled_by_customer'), ('rescheduled_by_customer', 'rescheduled_by_customer')], default='tentative', max_length=23),
        ),
        migrations.AlterField(
            model_name='slot',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 5, 7, 45, 42, 967802, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='slot',
            name='max_seats',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='slot',
            name='name',
            field=models.CharField(default='name', max_length=50),
        ),
        migrations.AlterField(
            model_name='slot',
            name='slot_duration',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='slot',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 5, 6, 45, 42, 967746, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='widget',
            name='button_text',
            field=models.CharField(default='Book it', max_length=100),
        ),
        migrations.AlterField(
            model_name='widget',
            name='calendar_type',
            field=models.CharField(choices=[('week', 'week'), ('list', 'list')], default='week', max_length=15),
        ),
        migrations.AlterField(
            model_name='widget',
            name='success_message',
            field=models.CharField(default='We have received your booking and sent a confirmation', max_length=300),
        ),
        migrations.AlterField(
            model_name='widget',
            name='time_format',
            field=models.PositiveIntegerField(choices=[(24, '24'), (12, '12')], default=24),
        ),
    ]
