# Generated by Django 2.2 on 2021-02-09 12:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('kit', '0002_auto_20210205_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 9, 13, 26, 31, 176156, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='slot',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 9, 12, 26, 31, 176103, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='WebhookTarget',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(default='https://webhook.site/709e296b-89eb-4cbc-b26f-8cbb8b6ddefc', max_length=255)),
                ('event', models.CharField(max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_targets', to='kit.Customer')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response_message', models.CharField(blank=True, max_length=1000)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('response_content_type', models.CharField(blank=True, max_length=1000)),
                ('is_sent', models.BooleanField(default=False)),
                ('attempt', models.IntegerField()),
                ('webhook_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='kit.WebhookTarget')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
